# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/PruebaC/PdfTools_Pdf2ImgSimple_C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/PruebaC/PdfTools_Pdf2ImgSimple_C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/PruebaC/PdfTools_Pdf2ImgSimple_C/CMakeFiles /workspaces/PruebaC/PdfTools_Pdf2ImgSimple_C//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/PruebaC/PdfTools_Pdf2ImgSimple_C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pdftoolspdf2imgsimple

# Build rule for target.
pdftoolspdf2imgsimple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pdftoolspdf2imgsimple
.PHONY : pdftoolspdf2imgsimple

# fast build rule for target.
pdftoolspdf2imgsimple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdftoolspdf2imgsimple.dir/build.make CMakeFiles/pdftoolspdf2imgsimple.dir/build
.PHONY : pdftoolspdf2imgsimple/fast

pdftoolspdf2imgsimple.o: pdftoolspdf2imgsimple.c.o
.PHONY : pdftoolspdf2imgsimple.o

# target to build an object file
pdftoolspdf2imgsimple.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdftoolspdf2imgsimple.dir/build.make CMakeFiles/pdftoolspdf2imgsimple.dir/pdftoolspdf2imgsimple.c.o
.PHONY : pdftoolspdf2imgsimple.c.o

pdftoolspdf2imgsimple.i: pdftoolspdf2imgsimple.c.i
.PHONY : pdftoolspdf2imgsimple.i

# target to preprocess a source file
pdftoolspdf2imgsimple.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdftoolspdf2imgsimple.dir/build.make CMakeFiles/pdftoolspdf2imgsimple.dir/pdftoolspdf2imgsimple.c.i
.PHONY : pdftoolspdf2imgsimple.c.i

pdftoolspdf2imgsimple.s: pdftoolspdf2imgsimple.c.s
.PHONY : pdftoolspdf2imgsimple.s

# target to generate assembly for a file
pdftoolspdf2imgsimple.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pdftoolspdf2imgsimple.dir/build.make CMakeFiles/pdftoolspdf2imgsimple.dir/pdftoolspdf2imgsimple.c.s
.PHONY : pdftoolspdf2imgsimple.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pdftoolspdf2imgsimple"
	@echo "... pdftoolspdf2imgsimple.o"
	@echo "... pdftoolspdf2imgsimple.i"
	@echo "... pdftoolspdf2imgsimple.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

